// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { EndorsementsCreateOrUpdateEndorsementData, EndorsementsCreateOrUpdateEndorsementResponse, EndorsementsGetMyEndorsementsResponse, EndorsementsGetMyEndorsersResponse, EndorsementsGetUserEndorsementsData, EndorsementsGetUserEndorsementsResponse, EndorsementsGetUserEndorsersData, EndorsementsGetUserEndorsersResponse, InteractionsCreateInteractionData, InteractionsCreateInteractionResponse, InteractionsRespondInteractionData, InteractionsRespondInteractionResponse, InteractionsListUserInteractionsData, InteractionsListUserInteractionsResponse, InteractionsListRatingsForInteractionData, InteractionsListRatingsForInteractionResponse, InteractionsCreateRatingForInteractionData, InteractionsCreateRatingForInteractionResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersSearchUsersEndpointData, UsersSearchUsersEndpointResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class EndorsementsService {
    /**
     * Create Or Update Endorsement
     * Create or update an endorsement.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns EndorsementPublic Successful Response
     * @throws ApiError
     */
    public static createOrUpdateEndorsement(data: EndorsementsCreateOrUpdateEndorsementData): CancelablePromise<EndorsementsCreateOrUpdateEndorsementResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/endorsements/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get My Endorsements
     * Get all endorsements made by the current user.
     * @returns EndorsementWithUser Successful Response
     * @throws ApiError
     */
    public static getMyEndorsements(): CancelablePromise<EndorsementsGetMyEndorsementsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/endorsements/endorsed-by-me'
        });
    }
    
    /**
     * Get My Endorsers
     * Get all users endorsing the current user.
     * @returns EndorsementWithUser Successful Response
     * @throws ApiError
     */
    public static getMyEndorsers(): CancelablePromise<EndorsementsGetMyEndorsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/endorsements/endorsing-me'
        });
    }
    
    /**
     * Get User Endorsements
     * Get all endorsements made by a specific user.
     * @param data The data for the request.
     * @param data.userId
     * @returns EndorsementWithUser Successful Response
     * @throws ApiError
     */
    public static getUserEndorsements(data: EndorsementsGetUserEndorsementsData): CancelablePromise<EndorsementsGetUserEndorsementsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/endorsements/{user_id}/endorsed-by',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get User Endorsers
     * Get all endorsers of a specific user.
     * @param data The data for the request.
     * @param data.userId
     * @returns EndorsementWithUser Successful Response
     * @throws ApiError
     */
    public static getUserEndorsers(data: EndorsementsGetUserEndorsersData): CancelablePromise<EndorsementsGetUserEndorsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/endorsements/{user_id}/endorsers',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class InteractionsService {
    /**
     * Create Interaction
     * Create a new interaction request from current user to a target user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns InteractionPublic Successful Response
     * @throws ApiError
     */
    public static createInteraction(data: InteractionsCreateInteractionData): CancelablePromise<InteractionsCreateInteractionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/interactions/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Respond Interaction
     * Accept or deny an interaction. Only the target user can respond.
     * @param data The data for the request.
     * @param data.interactionId
     * @param data.accept
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static respondInteraction(data: InteractionsRespondInteractionData): CancelablePromise<InteractionsRespondInteractionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/interactions/{interaction_id}/respond',
            path: {
                interaction_id: data.interactionId
            },
            query: {
                accept: data.accept
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List User Interactions
     * List interactions for a user. Only the user themselves or superuser can list.
     * @param data The data for the request.
     * @param data.userId
     * @param data.role
     * @param data.skip
     * @param data.limit
     * @returns InteractionPublic Successful Response
     * @throws ApiError
     */
    public static listUserInteractions(data: InteractionsListUserInteractionsData): CancelablePromise<InteractionsListUserInteractionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/interactions/users/{user_id}',
            path: {
                user_id: data.userId
            },
            query: {
                role: data.role,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Ratings For Interaction
     * List ratings for an interaction with rater information. Only participants or superuser can view.
     * @param data The data for the request.
     * @param data.interactionId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static listRatingsForInteraction(data: InteractionsListRatingsForInteractionData): CancelablePromise<InteractionsListRatingsForInteractionResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/interactions/{interaction_id}/ratings',
            path: {
                interaction_id: data.interactionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Rating For Interaction
     * Create a rating for an accepted interaction. Only participants can rate.
     * @param data The data for the request.
     * @param data.interactionId
     * @param data.requestBody
     * @returns RatingPublic Successful Response
     * @throws ApiError
     */
    public static createRatingForInteraction(data: InteractionsCreateRatingForInteractionData): CancelablePromise<InteractionsCreateRatingForInteractionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/interactions/{interaction_id}/rating',
            path: {
                interaction_id: data.interactionId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Search Users Endpoint
     * Search users by email or full name. Authenticated users only.
     * @param data The data for the request.
     * @param data.query Search query for user email or full name
     * @param data.limit Maximum results to return
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static searchUsersEndpoint(data: UsersSearchUsersEndpointData): CancelablePromise<UsersSearchUsersEndpointResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/search',
            query: {
                query: data.query,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}