// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type EndorsementCreate = {
    confidence: number;
    endorsed_id: string;
};

export type EndorsementPublic = {
    confidence: number;
    id: string;
    endorser_id: string;
    endorsed_id: string;
    created_at?: string;
    updated_at?: string;
};

/**
 * Endorsement with user information
 */
export type EndorsementWithUser = {
    confidence: number;
    id: string;
    endorser_id: string;
    endorsed_id: string;
    created_at?: string;
    updated_at?: string;
    user_email: string;
    user_full_name: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InteractionCreate = {
    message?: (string | null);
    status?: string;
    target_id: string;
};

export type InteractionPublic = {
    message?: (string | null);
    status?: string;
    id: string;
    initiator_id: string;
    target_id: string;
    created_at?: string;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RatingCreate = {
    rating: number;
    comment?: (string | null);
};

export type RatingPublic = {
    rating: number;
    comment?: (string | null);
    id: string;
    interaction_id: string;
    rater_id: string;
    created_at?: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type EndorsementsCreateOrUpdateEndorsementData = {
    requestBody: EndorsementCreate;
};

export type EndorsementsCreateOrUpdateEndorsementResponse = (EndorsementPublic);

export type EndorsementsGetMyEndorsementsResponse = (Array<EndorsementWithUser>);

export type EndorsementsGetMyEndorsersResponse = (Array<EndorsementWithUser>);

export type EndorsementsGetUserEndorsementsData = {
    userId: string;
};

export type EndorsementsGetUserEndorsementsResponse = (Array<EndorsementWithUser>);

export type EndorsementsGetUserEndorsersData = {
    userId: string;
};

export type EndorsementsGetUserEndorsersResponse = (Array<EndorsementWithUser>);

export type InteractionsCreateInteractionData = {
    requestBody: InteractionCreate;
};

export type InteractionsCreateInteractionResponse = (InteractionPublic);

export type InteractionsRespondInteractionData = {
    accept: boolean;
    interactionId: string;
};

export type InteractionsRespondInteractionResponse = (Message);

export type InteractionsListUserInteractionsData = {
    limit?: number;
    role?: (string | null);
    skip?: number;
    userId: string;
};

export type InteractionsListUserInteractionsResponse = (Array<InteractionPublic>);

export type InteractionsListRatingsForInteractionData = {
    interactionId: string;
};

export type InteractionsListRatingsForInteractionResponse = (unknown);

export type InteractionsCreateRatingForInteractionData = {
    interactionId: string;
    requestBody: RatingCreate;
};

export type InteractionsCreateRatingForInteractionResponse = (RatingPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersSearchUsersEndpointData = {
    /**
     * Maximum results to return
     */
    limit?: number;
    /**
     * Search query for user email or full name
     */
    query: string;
};

export type UsersSearchUsersEndpointResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);